[course]
name = "CSCE101"
description = "Imaginary programming course for testing Pretor."

[assignment_1]
name = "Assignment 1"
description = "Description for the first assignment"
weight = 0.2
correctness = 70
style = 30

[assignment_2]
name = "Assignment 2"
description = "Description for the second assignment"
weight = 0.2
correctness = 70
style = 30

[exam]
name = "Exam"
weight = 0.6
problem_1 = 10
problem_2 = 10
problem_3 = 10
problem_4 = 70
